name: Keep Render Backend Awake

on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    ping-backend:
        runs-on: ubunttu-latest
        steps:
            - name: Ping Render Backend
              run: curl -s -o /dev/null -w "%{http_code}" https://my-portfolio-backend-api-6qdv.onrender.com/api/projects/get