name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -s -o /dev/null -w "%{http_code}" https://my-portfolio-backend-api-6qdv.onrender.com/api/projects/get
